name       : python-qscintilla
version    : 2.13.1
release    : 21
source     :
    - https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.13.1/QScintilla_src-2.13.1.tar.gz : 800e3d2071a96bcccd7581346af0d2fe28fc30cd68530cb8302685d013afd54a
homepage   : https://www.riverbankcomputing.com/software/qscintilla/
license    : GPL-3.0-only
component  : programming
summary    : Python bindings for the QScintilla programmers editor widget
description: |
    QScintilla is a port to Qt of the Scintilla programmers editor widget.  It supports the traditional low-level Scintilla API and implements a high-level API covering such things as auto-completion, code folding and lexer configuration. These Python bindings implement a single extension module that sits on top of PyQt5 and wraps both the low-level and high-level APIs.
builddeps  :
    - pkgconfig(Qt5Widgets)
    - pkgconfig(python3)
    - pyqt-builder
    - python-pyqt5-sip
    - python-sip
    - python3-qt5
    - qscintilla-devel
rundeps    :
    - python3-qt5
replaces   :
    - python-qscintilla-qt5
setup      : |
    cd Python
    mv pyproject{-qt5,}.toml
    sip-build \
        --no-make \
        --qsci-features-dir ../src/features \
        --qsci-include-dir ../src \
        --qsci-library-dir ../src \
        --api-dir /usr/share/qt5/qsci/api/python
build      : |
    %make -C Python/build
install    : |
    %make_install -C Python/build INSTALL_ROOT="$installdir"
