name       : python-qscintilla
version    : 2.9.4
release    : 7
source     :
    - https://kent.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.9.4/QScintilla_gpl-2.9.4.tar.gz : 8b3a23023e9f0573caed6f9cee86f898d87b768ee15b8c211a423783a4cfa4e6
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python-3.5)
    - pkgconfig(QtCore)
    - pkgconfig(Qt5Widgets)
    - python3-qt5
    - python3-sip-devel
    - python-qt4
    - python-sip-devel
    - qscintilla-qt5-devel
    - qscintilla-devel
rundeps    :
    - python-qt4
    - qt5 :
        - python-qt5
setup      : |
    cp -R Python Python3
    # Python 2 / Qt4
    pushd Python
    python configure.py --pyqt=PyQt4
    pushd Qsci
    qmake-qt4 QMAKE_CFLAGS_ISYSTEM=-I \
              QMAKE_MOC=moc-qt4 \
              QMAKE_RCC=rcc-qt4 \
              QMAKE_UIC=uic-qt4
    popd
    %make
    %make_install INSTALL_ROOT=$installdir

    cd ../Python3
    # Python 3 / Qt5
    sed -i "s|self._find_exe('sip5', 'sip')|self.sip = self._find_exe('sip5', 'sip3')|" configure.py
    python3 configure.py --pyqt=PyQt5
build      : |
    cd Python3/Qsci
    %qmake QMAKE_CFLAGS_ISYSTEM=-I INCLUDEPATH+='/usr/include/QtWidgets /usr/include/QtPrintSupport' LIBS+='-lqscintilla2-qt5'
    cd ..
    %make
install    : |
    cd Python3
    %make_install INSTALL_ROOT=$installdir
patterns   :
    - qt5 :
        - /usr/lib/python3.5
        - /usr/share/qt5
        - /usr/share/sip/PyQt5
