name       : python-qscintilla
version    : 2.9.4
release    : 3
source     :
    - https://cytranet.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.9.4/QScintilla_gpl-2.9.4.tar.gz : 8b3a23023e9f0573caed6f9cee86f898d87b768ee15b8c211a423783a4cfa4e6
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(QtCore)
    - python-qt4
    - python-sip-devel
    - qscintilla-devel
rundeps    :
    - python-qt4
setup      : |
    cd Python
    python configure.py --spec=/usr/share/qt4/mkspecs/linux-g++ --qsci-incdir=/usr/include/qt4 --qmake=/usr/bin/qmake-qt4
build      : |
    cd Python
    sed -i "s|/usr/bin/moc|/usr/bin/moc-qt4|g" ./*/Makefile
    %make
install    : |
    cd Python
    %make_install INSTALL_ROOT=$installdir
