name       : python-qscintilla
version    : 2.10.2
release    : 14
source     :
    - https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.10.2/QScintilla_gpl-2.10.2.tar.gz : 14b31d20717eed95ea9bea4cd16e5e1b72cee7ebac647cba878e0f6db6a65ed0
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Widgets)
    - python3-qt5
    - python3-sip-devel
    - python-sip-devel
    - qscintilla-devel
rundeps    :
    - python3-qt5
replaces   :
    - python-qscintilla-qt5
setup      : |
    cp -R Python Python3-Qt5
    cp -R Python Python2-Qt5

    cd $workdir/Python3-Qt5
    # Python 3 / Qt5
    sed -i "s|self._find_exe('sip5', 'sip')|self.sip = self._find_exe('sip5', 'sip3')|" configure.py
    python3 configure.py --pyqt=PyQt5

    cd $workdir/Python2-Qt5
    # Python 2 / Qt5
    python2 configure.py --pyqt=PyQt5
build      : |
    cd Python3-Qt5/Qsci
    %qmake QMAKE_CFLAGS_ISYSTEM=-I INCLUDEPATH+='/usr/include/QtWidgets /usr/include/QtPrintSupport' LIBS+='-lqscintilla2_qt5'
    cd ..
    %make
    cd ..
    cd Python2-Qt5/Qsci
    %qmake QMAKE_CFLAGS_ISYSTEM=-I INCLUDEPATH+='/usr/include/QtWidgets /usr/include/QtPrintSupport' LIBS+='-lqscintilla2_qt5'
    cd ..
    %make
install    : |
    pushd Python3-Qt5
    %make_install INSTALL_ROOT=$installdir
    popd
    pushd Python2-Qt5
    %make_install INSTALL_ROOT=$installdir
    popd
