name       : python-qscintilla
version    : 2.9.3
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.9.3/QScintilla_gpl-2.9.3.tar.gz : 98aab93d73b05635867c2fc757acb383b5856a0b416e3fd7659f1879996ddb7e
license    : GPL-3.0
component  : programming.qt
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - glibc-devel
    - python-qt4
    - python-sip-devel
    - qscintilla-devel
rundeps    :
    - python-qt4
setup      : |
    cd Python
    python configure.py --spec=/usr/share/qt4/mkspecs/linux-g++ --qsci-incdir=/usr/include/qt4 --qmake=/usr/bin/qmake-qt4
build      : |
    cd Python
    %make
install    : |
    cd Python
    %make_install INSTALL_ROOT=$installdir
