name       : python-qscintilla
version    : '2.10'
release    : 4
source     :
    - https://versaweb.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10/QScintilla_gpl-2.10.tar.gz : 16be30577bc178470936c458551f2512cc068aff6e7a7de6ed244e28c045f6ec
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(Qt5Core)
    - python3-qt5
    - python3-sip-devel
    - qscintilla-qt5-devel
rundeps    :
    - python3-qt5
setup      : |
    cd Python
    python3 configure.py --pyqt=PyQt5
build      : |
    cd Python/Qsci
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
    cd ..
    %make
install    : |
    cd Python
    %make_install INSTALL_ROOT=$installdir
