name       : python-qscintilla
version    : '2.10'
release    : 5
source     :
    - https://versaweb.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10/QScintilla_gpl-2.10.tar.gz : 16be30577bc178470936c458551f2512cc068aff6e7a7de6ed244e28c045f6ec
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python-3.5)
    - pkgconfig(QtCore)
    - pkgconfig(Qt5Core)
    - python3-qt5
    - python3-sip-devel
    - python-qt4
    - python-sip-devel
    - qscintilla-qt5-devel
    - qscintilla-devel
rundeps    :
    - python-qt4
    - qt5:
        - python-qt5
setup      : |
    # Python 3 / Qt5 first
    cd Python
    python3 configure.py --pyqt=PyQt5
    cd Qsci
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
    cd ..
    %make
    %make_install INSTALL_ROOT=$installdir

    # Now Python 2 / Qt4
    python configure.py --pyqt=PyQt4
build      : |
    cd Python/Qsci
    qmake-qt4 QMAKE_CFLAGS_ISYSTEM=-I \
              QMAKE_MOC=moc-qt4 \
              QMAKE_RCC=rcc-qt4 \
              QMAKE_UIC=uic-qt4
    cd ..
    %make
install    : |
    cd Python
    %make_install INSTALL_ROOT=$installdir
patterns   :
    - qt5:
        - /usr/lib/python3.5
        - /usr/share/qt5
        - /usr/share/sip/PyQt5
