name       : python-qscintilla
version    : 2.11.6
release    : 15
source     :
    - https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.11.6/QScintilla-2.11.6.tar.gz : e7346057db47d2fb384467fafccfcb13aa0741373c5d593bc72b55b2f0dd20a7
homepage   : https://www.riverbankcomputing.com/software/qscintilla/
license    : GPL-3.0-only
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Widgets)
    - python3-qt5
    - python3-sip-devel
    - qscintilla-devel
rundeps    :
    - python3-qt5
replaces   :
    - python-qscintilla-qt5
setup      : |
    cp -R Python Python3-Qt5

    cd $workdir/Python3-Qt5
    # Python 3 / Qt5
    sed -i "s|self._find_exe('sip5', 'sip')|self.sip = self._find_exe('sip5', 'sip3')|" configure.py
    python3 configure.py --pyqt=PyQt5
build      : |
    cd Python3-Qt5/Qsci
    %qmake QMAKE_CFLAGS_ISYSTEM=-I INCLUDEPATH+='/usr/include/QtWidgets /usr/include/QtPrintSupport' LIBS+='-lqscintilla2_qt5'
    cd ..
    %make
install    : |
    pushd Python3-Qt5
    %make_install INSTALL_ROOT=$installdir
    popd
